//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushroomgamesOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desarrolladora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desarrolladora()
        {
            this.Juego = new HashSet<Juego>();
        }
    
        public string id_Desarrolladora { get; set; }
        public string nombre_Desarrolladora { get; set; }
        public string informacion_Desarrolladora { get; set; }
        public string direccion_Desarrolladora { get; set; }
        public string telefono_Desarrolladora { get; set; }
        public string correo_Desarrolladora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Juego> Juego { get; set; }
    }
}
