//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushroomgamesOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Descuentos()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public string id_Descuento { get; set; }
        public string nombre_Descuento { get; set; }
        public double cantidad_Descuento { get; set; }
        public string id_Juego { get; set; }
    
        public virtual Juego Juego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
