//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushroomgamesOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juego()
        {
            this.Descuentos = new HashSet<Descuentos>();
            this.Venta = new HashSet<Venta>();
        }
    
        public string id_Juego { get; set; }
        public string nombre_Juego { get; set; }
        public double precio_Juego { get; set; }
        public string descripcion_Juego { get; set; }
        public string tamanio_Juego { get; set; }
        public string id_Categoria { get; set; }
        public string id_Desarrolladora { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Desarrolladora Desarrolladora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Descuentos> Descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
