//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushroomgamesOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public string id_Usuario { get; set; }
        public string nombre_Usuario { get; set; }
        public string apellidoPaterno_Usuario { get; set; }
        public string apellidoMaterno_Usuario { get; set; }
        public string direccion_Usuario { get; set; }
        public string telefono_Usuario { get; set; }
        public string fechaNacimiento_Usuario { get; set; }
        public string sexo_Usuario { get; set; }
        public string correoElectronico_Usuario { get; set; }
        public string targetaCredito_Usuario { get; set; }
        public string contrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
