//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushroomgamesOrd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public string folio_Venta { get; set; }
        public string id_Juego { get; set; }
        public string id_Usuario { get; set; }
        public string id_Descuento { get; set; }
        public string precioJuego_Venta { get; set; }
        public string fecha_Venta { get; set; }
    
        public virtual Descuentos Descuentos { get; set; }
        public virtual Juego Juego { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
